### ISSUE TITLE
EBU-TT to DXFP

### ISSUE THREAD

**Issue by ggodart** [IRT-Open-Source/scf#7]
It would be useful for an XSLT translation for EBU-TT to DXFP for deployments wishing to use Microsoft Smooth streaming of subtitles.
We believe this would be a pretty simple edit of the EBU-TT to EBU-T-D template to exchange the namespaces of EBU-TT-D and take out few extensions.

**Comment by nigelmegitt** [comment]
If the Smooth player is TTML compliant then it should play EBU-TT and EBU-TT-D already. (DFXP is a TTML profile, and EBU-TT is based on it already) Can you describe any further constraints of the Smooth player to permit playback of DFXP format subtitles? What happens if you provide an EBU-TT file to a Smooth player now?

**Comment by ggodart** [comment]
I'm not able to do this at the moment (I don't have any streams) has anyone else tried it?

**Comment by tairt** [comment]
One TTML2DFXP module is provided with commit ea409d078ff322c7206700baa341ac4db81fee69. This module could also be used to solve the use case by  @ggodart (convert EBU-TT to DFXP).
